### ISSUE TITLE
Surface

### ISSUE THREAD

**Issue by MonZop** [MonZop/BioBlender#1]
The molecular surface is not calculated.
In theory, BioBlender should send the atomic coordinates to pyMOL (distributed with BioBlender), which would read the file (pdb format), calculate the surface and return it to BioB as a wrl file. I do not know where is the problem.

**Comment by zeffii** [comment]
is this the error?
```
Setup is complete!
Running PyMLP
PyMLP command succeded
Making Surface using PyMOL
The filename, directory name, or volume label syntax is incorrect.
Failed to open file: C:\blender_trunk\2.73\scripts\addons_contrib\BioBlender\tmp\tmp.wrl
```

**Comment by MonZop** [comment]
Hi, thanks for trying to fix this. I get this error:
pE: None
Generate Surface Failed: bpy_prop_collection[key]: invalid key, must be a string
 or an int, not NoneType

We selected pyMOL to calculate the surface because it generates a nice mesh, well triangulated and with few internal disconnected surfaces. Until few years ago it was distributed as Open source, and it was very easy to install. Other alternative methods for surface generation are available, if pyMOL becomes a problem

**Comment by zeffii** [comment]
From my limited knowledge of PyMOL it is still entirely open-source, just one might pay for the convenience of acquiring a precompiled version. Compilation can be a painful experience.

**Comment by zeffii** [comment]
Out of interest, what changed before the surface feature broke? Are you using this on a new version of an operating system ..or new version of blender? Without a PyMOL.exe to test I can't be much use i'm afraid.

**Comment by MonZop** [comment]
My best guess is that pyMOL used python 2.6. Now there is a new version of python and somthing got wrong. I cannot get a surface even using BioBlender 0.6, which is a patched version of Blender with BioBlender already included and compiled. 
But it still works in an old pc that we have not updated.

**Comment by zeffii** [comment]
it's OK to have multiple versions of Python on one machine ( I have `2.6`, `2.7`, `3.3`, `3.4`).

Maybe this will throw some light:
- What operating system are you on?
- What version of python starts when you go to console/command prompt and type `python`
- What happens when you type `pymol` , does it find the executable ?

**Comment by MonZop** [comment]
Window 7
Python 2.7.2
it does not find it. I'll try to place pyMOL where it can be found

**Comment by zeffii** [comment]
@MonZop you should be able to leave the location of PyMOLwin.exe unchanged. I imagine they are something like 
```
"%programfiles%\\PyMOL\\PyMOL\\PymolWin.exe",
"%programfiles%\\DeLano Scientific\\PyMOL Eval\\PymolWin.exe",
"%programfiles%\\DeLano Scientific\\PyMOL\\PymolWin.exe",
"%programfiles(x86)%\\PyMOL\\PyMOL\\PymolWin.exe",
"%programfiles(x86)%\\DeLano Scientific\\PyMOL Eval\\PymolWin.exe",
"%programfiles(x86)%\\DeLano Scientific\\PyMOL\\PymolWin.exe",
```

**Comment by zeffii** [comment]
here 
'%programfiles%' would mean something like `C:\Program Files` 
and 
%programfiles(x86)%' would mean something like `C:\Program Files (x86)`

**Comment by zeffii** [comment]
I now have pymol installed so can experiment with surface generation too

**Comment by zeffii** [comment]
```
PDB String
Bootstrapping
create_fi_materials
get_new_PDB_id
appending file
appending file
Import Preview
Import Ready: True
core_import_File
get_num_model: [1, 2, 3]
core_parse_pdb
A
core_sort_hr
appending file
core_create_Models
added KF from core create models function
added KF from core create models function
Empty Chains creation
cleaning up
atom_action
pdbID: 2
session_save
Warning: Blender file needs to be saved first to create persistent session data
Finished Importing!
pE: s_wH
pdppath: C:\blender_trunk\2.73\scripts\addons_contrib\BioBlender\Test_molecules\01_CaM_Protein3Conformations_wH.
PDB
Trying to making dir on Win (no TMP folder)...
Precopy
Exporting PDB...
=============== exporting PDB
Exporting model 's_wH' to C:\blender_trunk\2.73\scripts\addons_contrib\BioBlender\tmp\tmp.pdb
=======outPath = C:\blender_trunk\2.73\scripts\addons_contrib\BioBlender\tmp\tmp.pdb
Setup is complete!
Running PyMLP
PyMLP command succeded
Making Surface using PyMOL

C:\blender_trunk\2.73\scripts\addons_contrib\BioBlender\tmp\tmp.pdb was parsed ... 1167 lines were taken into ac
count

Grid dimension (angstroms):
coord : min       max       ngrid
    x : -25.4145  51.5855       77
    y : -26.9150  42.0850       69
    z : -28.9510  29.0490       58


Grid Points Coordinates evaluated

Calculation in progress :    73.11%Info: Removed 214984 vertices

Calculation in progress :   100.00%

MLPmin =   -2.778 | MLPmax =    0.646 | MLPmean =   -0.109


Molecular Lipophilic Potential Map saved in C:\blender_trunk\2.73\scripts\addons_contrib\BioBlender\tmp\tmp.dx

Bye ...

Loading MLP values into Blender
Info: Removed 0 vertices

MLP function completed
```
![image](https://cloud.githubusercontent.com/assets/619340/5987874/56a82eae-a944-11e4-9a84-14a3786e5043.png)

to me this suggests, the existing routine is fine.. and it's a path issue on your win7 machine

**Comment by MonZop** [comment]
GREat!!
I'll find someone to help me fix it!
(not before monday)

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/5988274/dffd3ea0-a959-11e4-9249-58d63da45ca7.png)

**Comment by zeffii** [comment]
Seen as the surface is calculated by passing data from BioBlender to pymol and back it might help to point out how I installed pymol for windows legally from source.
- I don't use PyMOLwin.exe but instead pymol.cmd
- my path to `pymol.cmd` is `C:\Python27\Scripts\pymol.cmd`
- the equivalent of this in `pyMolPathSearch` is `"%systemdrive%\\Python27\\Scripts\\pymol.cmd"`
- the extra path is added to the experimental BB 273 version.
- installation of pymol proceeded with some confusion, but eventually the steps:
    - install pip for python 2.7
        -  this creates  `C:\Python27\Scripts\pip2.7.exe`
        - you need this file before any of the following commands will make sense.
    - http://www.lfd.uci.edu/~gohlke/pythonlibs/#pymol download the 2.7 version (not launcher) `(whl)`
    - http://www.lfd.uci.edu/~gohlke/pythonlibs/#pmw download the py2 version `(whl)`
    - instructions how to install a whl file:
        -  https://pip.pypa.io/en/latest/user_guide.html#installing-from-wheels
    - install pwm for python 2.7 (whl)
        - from inside C:\Python27\ i ran 

            ```
            # i typed the full path to pip2.7.exe, incase pip for 
            # other version of python got in the way
            C:\Python27\Scripts\pip2.7.exe pip install Pmw‑2.0.0‑py2‑none‑any.whl
            ```

    - install pymol for python 2.7 (whl)
        - from inside C:\Python27\ i ran 

            ```
            C:\Python27\Scripts\pip2.7.exe pip install pymol‑1.7.2.1‑cp27‑none‑win32.whl
            ```

**Comment by zeffii** [comment]
Surface also generates a Vertex Color map : 

![image](https://cloud.githubusercontent.com/assets/619340/6000753/0b1b84c8-aae2-11e4-98f7-ce2e430a5dc0.png)

**Comment by MonZop** [comment]
WOW!!
What molecule is this?
And how did you get the color map? Is it the lipophilic potential? (it does not look like...)
It seems a very good step forward, but I do not understand very well 
(besides, I am still fighting with Blender 273, which crashes immediatelty at start)

**Comment by zeffii** [comment]
05_glycoprotein_4AY9_FSH

OK let's deal with Blender crashing separately

**Comment by zeffii** [comment]
Are you able to get the surface generated yet? -- if not does the console/terminal show any warnings?

**Comment by MonZop** [comment]
Yes, I do get the PyMOL generated surface.
No MLP visulization at all; not atomic and not integrated onthe surface...

**Comment by zeffii** [comment]
OK, what should that produce visually?

**Comment by MonZop** [comment]
![untitled](https://cloud.githubusercontent.com/assets/10231334/6061199/ee9f7f96-ad45-11e4-85df-f3c1db3c5697.png)
this is the first mapping in grey scale. Then it is rendered as a combined  scale : from dark, opaque, rough to white, shiny, smooth (hydrophilic to lipophilic)

**Comment by MonZop** [comment]
![rendertest](https://cloud.githubusercontent.com/assets/10231334/6061303/d582b112-ad46-11e4-8314-e730c78395a0.png)
rendered (in this case only rough/smooth and matte/shiny, without the color gradient)

**Comment by MonZop** [comment]
![atomicmlp](https://cloud.githubusercontent.com/assets/10231334/6078362/0f29c796-adf8-11e4-824b-f7beeae067ce.png)
And this is the Atomic MLP view.

**Comment by MonZop** [comment]
The logical steps are:
Use pyMLP to attribute to each atom its fi value (I was surprised to find the fi values in the main script)
Integrate the values usign the formula of your choice (Testa is default), and produce a file .dx containing the grid of values in the 3D space of the ,molecule.
For each vertex of the mesh, interpolate the local vaule in the grid, and attribute the value to the vertex, in a file .obj, with x,y,z and the resulting value in u
Now the file can be sent to Blender, that will:
transform the vertex u into a scale of greys (after normalizing the values to 0-1); and build a grey UV map;
use the  map for color; for adding bump and specular features to the mesh.
The atomic MLP is a simple attribution of grey to each atom, represented in the VanderWaals sphere.
