### ISSUE TITLE
[SOLVED] Blender Crashes on program load

### ISSUE THREAD

**Issue by zeffii** [MonZop/BioBlender#10]
This could be many things, but i'll ignore that and try to get you to use a [builder.blender.org version](https://builder.blender.org/download/) 
(it will be slightly newer and have some bugfixes over the official 2.73a, it may also have new and exciting bugs...)

- go to [builder.blender.org](https://builder.blender.org/download/)
- obtain the archive suitable for your Operating System (careful 32bit or 64bit)
- create folder (if you have permission) called `blender_trunk` somewhere on your machine:
    - I have a folder called `blender_trunk` directly inside _C:\_ , so `C:\blender_trunk`
- unpack the file, then go into the folder which will read something like : `blender-2.73-8cd106f-win32`
- inside this folder you will see a 2.7x folder and a whole bunch of blender files.
![likeso](https://cloud.githubusercontent.com/assets/619340/6005327/dcbf89e4-ab09-11e4-82fe-2d80fa7ec1cd.gif)

- then drag over the content of that entire that folder into `C:\blender_trunk`, so the content looks like

![image](https://cloud.githubusercontent.com/assets/619340/6004110/c1a37cfa-ab00-11e4-8c4b-e6f52a88351b.png)

what happens if you click on that `blender.exe` ? 

If it still crashes, it may be worth trying to launch blender from a command prompt / terminal, to see if there are any error messages.

**Comment by MonZop** [comment]
With the help of a colleague, we did just that, plus area more attempts. the result is invariably that blender starts and crashes immediately.
in the blender report there is no help,either...

**Comment by zeffii** [comment]
ok.. all is not lost yet! 
```
C:\Users\your_user_name\AppData\Roaming\Blender Foundation\Blender\2.73
```
delete all content in that folder

**Comment by zeffii** [comment]
When you start blender from a command prompt, what does it say?
![image](https://cloud.githubusercontent.com/assets/619340/6005654/53212d48-ab0c-11e4-93a2-a3d10bd0ba7c.png)

![image](https://cloud.githubusercontent.com/assets/619340/6005667/6f2de5c6-ab0c-11e4-99c1-5b47e4c0964d.png)

**Comment by zeffii** [comment]
reading through the bug tracker of blender.org, there's a scenario which appears much like the one you  describe. It involves something called a (forgive the caps) `PYTHONPATH`. 

in a console/terminal type: `SET` or `set` and windows will spit out a bunch of environmental variables.
![image](https://cloud.githubusercontent.com/assets/619340/6007061/c22f3e54-ab17-11e4-9610-e87517dc7e30.png)


 If `PYTHONPATH` is among those, and it points to a 2.6 or 2.7 version of Python, this may indicate

**Comment by MonZop** [comment]
Path=C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windo
ws\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Python27;C:\Pyth
on27\Scripts


There is not a specific PYTHONPATH; Python is mentioned in the lines copied above

**Comment by zeffii** [comment]
hmm, nope that's not it then.. i'll do some more digging

**Comment by MonZop** [comment]
Following another clue (http://blenderartists.org/forum/showthread.php?359439-Blender-2-73-Crashes-at-Startup) , I updated Windows to the latest ; 
unfortunately the result is the same: immediate crash of Blender 
(maybe this is an issue for the BF developers?)

**Comment by zeffii** [comment]
it's win7 64bit? Do you have admin rights, can you freely install stuff. Uni computers tend to come with certain restrictions, and sometimes background monitoring processes that close programs which are not in some white-list of allowed executables.

i'd be interested to know a few more things, before doing a bug report to BF developers.
- what happens if you start blender from `blender-app.exe` 
- what happens if you start blender from command-line using `blender.exe --debug-all` (this might spit out a bunch of data but it should stay on screen so you can read the last few lines -- the last lines tend to be informative in these scenarios)

**Comment by MonZop** [comment]
Yeas, I do have full control on the pc. It is a Windows7, 64 bits (I even tried to install the 32 bit, but it crashes).

 With blender-app.exe same result

**Comment by MonZop** [comment]
with blender.exe --debug-all I get what you said. 
How do I paste here the copy of command window?
However the last lines are:
ghost_event_proc: window 1 state = normal
Thread 0: update object OBLamp
Thread 2: update object OBCamera
recalcob Camera
recalcob Lamp
Thread 4: update object OBCube
recalcob Cube
recalcdata Cube
Thread 0: total 1 objects in 0.000121 sec.
  Lamp in 0.000121 sec
Thread 1: total 0 objects in 0.000000 sec.
Thread 2: total 1 objects in 0.000064 sec.
  Camera in 0.000064 sec
Thread 3: total 0 objects in 0.000000 sec.
Thread 4: total 1 objects in 0.000097 sec.
  Cube in 0.000097 sec
Thread 5: total 0 objects in 0.000000 sec.
Thread 6: total 0 objects in 0.000000 sec.
Thread 7: total 0 objects in 0.000000 sec.
ED_screen_refresh: set screen
ghost_event_proc: ghost redraw 1
ghost_event_proc: ghost redraw 1
GL error: enumeratore non valido
Writing: C:\Users\Monica\AppData\Local\Temp\blender.crash.txt

The file crash.txt says: 
# Blender 2.73 (sub 0), Commit date: 2015-01-20 18:16, Hash bbf09d9
bpy.ops.wm.splash()  # Operator

# backtrace

**Comment by MonZop** [comment]
Ops, sorry about the size: i have no control of it

**Comment by MonZop** [comment]
The line fomr the black window that says: 
GL error:enumeratore non valido
means invalid enumerator 
might this be the problem?

**Comment by MonZop** [comment]
![senzanome](https://cloud.githubusercontent.com/assets/10231334/6021064/f12bce34-abb2-11e4-9015-bb107f90dd4f.jpg)

**Comment by zeffii** [comment]
no, GL_errors are most probably false positives. The `--debug-all` is like a fishing net which also catches the occasional octopus.

**Comment by zeffii** [comment]
The first thing the guys in Blender's bug tracker will ask is to try with a latest builder-bot version too. The error you pasted (not the image) shows the last blender.crash.txt was generated by a blender.exe which was created 2015-1-20 (two weeks ago). 

At this point you have several 64bit versions of 2.73 on your machine, but the most interesting feedback will be if you do a debug from one of the `builder-bot` versions. (the zips, like: blender-2.73-280ed32-win64`, where `280ed32` is the hash / unique identifier.

literally: 

- create a folder on `C` called `blender_trunk` 
- drag one of the `builder-bot` builds into that
- start blender.exe from there with the debug flag,
    -  it would be `C\blender_trunk\blender.exe --debug-all` . 
    - or 
    - `C:\blender_trunk\blender-2.73-280ed32-win64\blender.exe --debug-all`

This is a real pain. The solution should be torturously simple.

**Comment by MonZop** [comment]
Done: 
![blackwindow2](https://cloud.githubusercontent.com/assets/10231334/6022005/1b74ac5e-abba-11e4-87a8-f2a2a5918337.png)

**Comment by zeffii** [comment]
there is no space between `--debug-all`

**Comment by MonZop** [comment]
repeated without mistake (space between --debug and  -all)
![blackwindow3](https://cloud.githubusercontent.com/assets/10231334/6022045/7109283e-abba-11e4-8986-66ea46fcf66c.png)

**Comment by zeffii** [comment]
Cool! i'll ask around. At this point it beyond what I know how to fix

**Comment by MonZop** [comment]
Thanks
(in the meanwhile, I have to remove all 2.73, and re-install 2.70, if I want to do some work!)

**Comment by zeffii** [comment]
you can have multiple blender installations on the same machine, you can set up shortcuts to each of the executables..

**Comment by zeffii** [comment]
```
<mont29> zeffii: Please:
<mont29> * Ensure both your OS and drivers are fully up-to-date.
<mont29> * Ensure your GPU driver supports at least OpenGL 1.4.
<mont29> * Ensure you have installed MSVC2013 redistributable package (http://www.microsoft.com/en-us/download/details.aspx?id=40784).
<mont29> * Try to disable any running antivirus.
<mont29> * Ensure you have no python executable available in your %path% envvar.
<mont29> * Try to re-download and re-install Blender.
<mont29> * Try to start Blender in factory settings (`--factory-startup` commandline option).
<mont29> * Try to place [this dll](http://download.blender.org/ftp/sergey/softwaregl/win64/opengl32.dll) next to your blender.exe (software OGL, will be slow, but will show whether this is a driver issue or not).
```

**Comment by MonZop** [comment]
I'll need a day only to understand all of this!
;-)
But will try
OS fully updated, already done...

**Comment by MonZop** [comment]
BINGO!!
I updated the NVIDIA driver.
I thought that all updates were done automatically, but clearly this was not the case.
Inow have Blebder 273, and can start checking BioBledner 
Jumps up and down!!

**Comment by zeffii** [comment]
AWESOME/.

now we ROK ON!

**Comment by zeffii** [comment]
still, advice is to use the latest `builder bot version` or `2.73a`  (I tend to use the builder bot because it fixes tonnes of bugs in-between the major releases)

**Comment by webdev20** [comment]
I got the same problem, and after I tried to run from command prompt, I found that it was trying to open a file named `quit.blend` located on my Temp directory.

> C:/Users/My Username/AppData/Local/Temp/quit.blend

I deleted that file and blender launched normally.

**Comment by donmckenna** [comment]
I had a similar issue but I actually couldn't get Blender to open certain files at all.
But @mernstackman's `Temp` path showed I had some semi-recent Blender autosaves there of the files with issues.
The autosaves opened fine and I was able to save-as them as new files which also work fine.
Not sure what actually caused this though..
