### ISSUE TITLE
BB2 doesn't import all conformations.

### ISSUE THREAD

**Issue by zeffii** [MonZop/BioBlender#15]
@MonZop found:
> The file contains 4 MODELS (conformations), but I noticed that BB2 only imports 3 of them. I also tried to import other proteins that have many conformations, but BB2 imports all models except the last one.

This seems like an _off by one_ error or other indexing mistake.

**Comment by zeffii** [comment]
just to be clear, this means all files with _N_ conformations, only import _N - 1_ of those? It's not just the `06_1L2Y_4LGE.pdb`

**Comment by MonZop** [comment]
exactly: all tested files import all conformations -1

**Comment by MonZop** [comment]
The last version 273_compatible, downloaded 10 minutes ago, does import all conformations, in some cases (I still have not clear which are OK and which are not)

**Comment by zeffii** [comment]
I think it may be something simple, but haven't tracked it down yet.

**Comment by zeffii** [comment]
**problem case**

The `06_1L2Y_4LGE.pdb` test pdb, has 4 conformations (named 1,3,4,5) but only keyframes 1,3,4 are created 

time for some process of elimination and some assumptions.

- It appears that in the above example conformation 5 is stored, but it's empty
- In a test .pdb `06DEBUG_1L2Y_4LGE.pdb` i renamed the conformations to 1,2,3,4, and then only 1,2,3 are created. This was to see if perhaps the bug was related to the sequence of names.
- this means that the error is not likely in `core_createModels()` but earlier, probably in the construction of `pdbIDmodelsDictionary[pdbID]`

**Comment by MonZop** [comment]
I think that when BB 'make preview' of a file, it makes a copy that is stored in some temporarty file. This is because sometimes pdb files are fetched directly from the databank, and it is useful to have a local copy.

**Comment by zeffii** [comment]
Right! The `importPreview` function (when successful) will either obtain the pdb from [pdb.org]() or _read the local file_ . The function does not edit the file, merely gather information. The error isn't there (at least, i've read it carefully, and it appears OK)

**Comment by zeffii** [comment]
it's narrowed down to the `core_parsePDB` function.  It's not a big function, so I expect progress today.

**Comment by zeffii** [comment]
cool. I'm pretty sure it's this, the last line flattens the dict.. 
```python
			# when the end of a tmpPDBmodelDictionary is reached, add the tmpPDBmodelDictionary dictionary to the list
			if tag == "ENDMDL" or tag=="END" or tag == "MODEL" and (tmpPDBmodelID in tmpPDBmodelImportOrder):
				# We add a new MODEL entry to the global pdbIDmodelsDictionary[pdbID],
				# based on the current MODEL ID, and we assign the tmpPDBmodelDictionary to this entry.
				(pdbIDmodelsDictionary[pdbID])[tmpPDBmodelID] = tmpPDBmodelDictionary
				# So now pdbIDmodelsDictionary[pdbID] is a Dictionary: model-dict; the second dict is [atomName]-BBInfo
				tmpPDBmodelDictionary = {}
```

**Comment by MonZop** [comment]
Great!
I have no doubt that having found the problem you also have the solution!
(always thankful)

**Comment by zeffii** [comment]
yeah, fixing is the easy part! finding, can be a slow process (but i should really have found this sooner)

**Comment by zeffii** [comment]
There are some subtleties in the pdb file format specs,  this is what's happening:
```
tmpPDBmodelID 1 : 0   (size)
tmpPDBmodelID 1 : 154
tmpPDBmodelID 3 : 0
tmpPDBmodelID 3 : 154
tmpPDBmodelID 4 : 0
tmpPDBmodelID 4 : 154
tmpPDBmodelID 5 : 0
tmpPDBmodelID 5 : 154
tmpPDBmodelID 5 : 0           <-- the final call wipes the content.
core_sort_hr
```

**Comment by zeffii** [comment]
Will have to read slowly: http://www.biostat.jhsph.edu/~iruczins/teaching/260.655/links/pdbformat.pdf

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/6155243/0c78d62a-b232-11e4-9645-c11e87f3a6e3.png)

if the pdb is always formatted in a certain way (for multiple conformations), like:
```
MODEL   1
ATOM
ATOM
ATOM
...
TER
ENDMOL
MODEL    2
ATOM
ATOM
ATOM
...
TER
ENDMOL
END
```
but as mentioned, i'm assuming there are deviations possible to the way programs write this sequences.
@MonZop or can you show other permutations or is this the only valid way to encode multiple conformations in one file?

**Comment by MonZop** [comment]
To my knowledge all pdb files should be formatted as you show. The committee that run the repository ( Protein Data Bank), check that all submissions comply. there are discussions about new pdb formats, especially for huge molecular complexes (millions of atoms), but for now the known pdb format shiuld be safe

**Comment by MonZop** [comment]
For data obtained by molecular dynamics there is a different format, which includes a single pdb descrption and the trajectory for each atom. Readers for this format are available, but i would leave this issue for a next development of bioblender

**Comment by zeffii** [comment]
OK, then the current branch https://github.com/MonZop/BioBlender/tree/master_mff_experiments
is reasonably the next _pull request_. Try it.

**Comment by MonZop** [comment]
Yes, tomorrow

**Comment by MonZop** [comment]
![bb2addon](https://cloud.githubusercontent.com/assets/10231334/6166661/5bd0740a-b2b2-11e4-91c5-dd59311f642b.png)
oh oh, something's wrong..

**Comment by MonZop** [comment]
![details](https://cloud.githubusercontent.com/assets/10231334/6166722/0fda5862-b2b3-11e4-9789-ed88e167a06c.png)
Maybe this helps?

**Comment by zeffii** [comment]
Everything will be OK :)

The problem here luckily is not the addon, but how the addon is installed. In my opinion this is a general flaw in the add-on installation / storage mechanism of Blender itself. Hopefully I can explain.

**Comment by zeffii** [comment]
This has to do with how to test Branches.

on windows scripts / add-ons can be stored in 2 main areas
```
[1] C:\Program Files\Blender Foundation\Blender\2.73\scripts\addons\BioBlender
[2] C:\Users\Username\AppData\Roaming\Blender Foundation\Blender\2.73\scripts\addons\BioBlender
```
remember that the current master on github is something you can revert back to easily if everything fails.
I propose that for convenience you:

**with Blender closed**
-  delete BioBlender from `[1]`. (Any any branches you may have dragged in)
-  delete all branches you may have installed in [2] (perhaps `BioBlender-master-first-fixes`,  ..etc.  *except* `BioBlender-master-mff-experiments`. Also delete the `BioBlender` folder. The only mention remaining of BioBlender inside addons would then be `BioBlender-master-mff-experiments`.
- rename `BioBlender-master-mff-experiments` to `BioBlender`. 

**with Blender open**
- go to user preferences / addons and untick any BioBlender (or Branches)
- Save User Settings
- hit Refresh.
- Close and re open  Blender
- enable the BioBlender addon. 
- Save User Settings.

**Comment by zeffii** [comment]
The folder which contains all the BioBlender content must now be called `BioBlender`, if its `BioBlender-master-mmf-experiments` rename it. If you don't want to lose your current stable BioBlender folder you could first rename that to `BioBlender-stable-todaysdate`. (Blender won't look for this folder, and it will not conflict)

- If the experimental version is OK, that's great (that's the goal anyway)
- if not OK, then you close Blender, 
   - delete the `BioBlender` folder, 
   - and rename `BioBlender-stable-todaysdate` to `BioBlender`

**Comment by zeffii** [comment]
I've just pushed a change to `BioBlender-master-mmf-experiments` which allows you to name the folder whatever you want. But having multiple version of that addon in the addons directory is a headache I avoid by using the GitHub desktop application.

**Comment by MonZop** [comment]
`C:\blender_trunk\blender-2.73-8cd106f-win64\2.73\scripts\addons` 
`C:\Program Files\Blender Foundation\blender-2.73a-windows64\2.73\scripts\addons`
`C:\Program Files\Blender Foundation\Blender\2.73\scripts\addons`
`C:\Users\Monica\AppData\Roaming\Blender Foundation\Blender\2.73\scripts\addons`

I have looked for BioBlender AddOn in all these places, but found it nowhere.
All the zip BioBlender versions are in another folder, that does not contain Blender.
I finally renamed the very latest (just downloaded) version to BioBlender2, and it still get the warining, but it does install BB2.

Now I can test it!

**Comment by zeffii** [comment]
if it imports all conformations from 01 and 04 pdb, then you know it's running the right versions. Hopefully the EP lines are also more accurate

**Comment by MonZop** [comment]
Import is OK, all confomrations (up to 38, just tested)

**Comment by MonZop** [comment]
EP lines also look good

**Comment by MonZop** [comment]
Will have to check line animation (re-calculation of lines during protein motion)

**Comment by zeffii** [comment]
in function `core_parsePDB`, the solution which is simplest and seems to behave well for the demo .pdb files is, instead of this

```python
# when the end of a tmpPDBmodelDictionary is reached, add the tmpPDBmodelDictionary dictionary to the list
if tag == "ENDMDL" or tag=="END" or tag == "MODEL" and (tmpPDBmodelID in tmpPDBmodelImportOrder):
    # We add a new MODEL entry to the global pdbIDmodelsDictionary[pdbID],
    # based on the current MODEL ID, and we assign the tmpPDBmodelDictionary to this entry.
    (pdbIDmodelsDictionary[pdbID])[tmpPDBmodelID] = tmpPDBmodelDictionary
    # So now pdbIDmodelsDictionary[pdbID] is a Dictionary: model-dict; the second dict is [atomName]-BBInfo
    tmpPDBmodelDictionary = {}
```
it's this:
```python
# when the end of a tmpPDBmodelDictionary is reached, add the tmpPDBmodelDictionary dictionary to the list
if tag == "ENDMDL" or tag=="END" or tag == "MODEL" and (tmpPDBmodelID in tmpPDBmodelImportOrder):
    # We add a new MODEL entry to the global pdbIDmodelsDictionary[pdbID],
    # based on the current MODEL ID, and we assign the tmpPDBmodelDictionary to this entry.
    if tmpPDBmodelDictionary:
        # don't push an empty tmpPDBmodelDictionary onto pdbIDmodelsDictionary.
        (pdbIDmodelsDictionary[pdbID])[tmpPDBmodelID] = tmpPDBmodelDictionary
    # So now pdbIDmodelsDictionary[pdbID] is a Dictionary: model-dict; the second dict is [atomName]-BBInfo
    tmpPDBmodelDictionary = {}
```

**Comment by zeffii** [comment]
this fixes multi-conformation pdb import and doesn't appear to have negative side effects with other kinds of pdb. Closing for now
