### ISSUE TITLE
import pdb error 'Problem in import EmptySet.blend: '

### ISSUE THREAD

**Issue by zeffii** [MonZop/BioBlender#4]
```
Import Failed: ('Problem in import EmptySet.blend: ', 
AttributeError('Calling operator "bpy.ops.wm.link_append" error, could not be found',))
```
windows / latest BioBlender 2.

Perhaps I can be of some assistance with the Python, even If I know little about Biology past 3rd year of high school.

http://blender.stackexchange.com/a/17879/47
(`wm.link_append` no longer exists in Blender 2.7+. ) it's either .link or .append

`bpy.ops.wm.append(filepath = Path, filename = objName, directory = Directory)`

**Comment by zeffii** [comment]
I'll fix this in a [Fork](https://github.com/zeffii/BioBlender), but perhaps you would like to give me access to this Repository as a Contributor to minimize the occurrance that people start doing the same work.

check my other github stuff, it's almost all Blender related

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/5893099/407d08b8-a4d8-11e4-9b58-f155143a1b18.png)

**Comment by MonZop** [comment]
Hi, 
I have to check what it means and implies, and how to do to give you contributor status. Possibly later today (I am learning step by step as I go).

**Comment by MonZop** [comment]
(even ofr words like open and close, I am not sure what they mean!)

**Comment by zeffii** [comment]
I'm still reading through the source, it's a monster! 4k lines in one file is something I'd like to avoid by using modules for clear separation of behaviours. I'm slowly refactoring in my own Fork.

I'd like to help, but let's both set our Hope to neutral for the time being :)

**Comment by MonZop** [comment]
I have just added you as a Collaborator.
If this is the same as Contributor, I think you have now access to all functions in this repository

**Comment by zeffii** [comment]
Cool. It is always possible to remove me as as Collaborator or Contributor should you want to.

I have questions relating to supporting 2.73 onwards. Generally it is good to keep the topics of these issues in the issue tracker highly separated to allow others to find information faster.
