### ISSUE TITLE
undeclared function

### ISSUE THREAD

**Issue by zeffii** [MonZop/BioBlender#5]
https://github.com/MonZop/BioBlender/blob/master/BioBlender2.py#L421

Refers to `boostrap()` as a function, but this doesn't exist anywhere in the repo (no automated searches found it anyway) , should be `bootstrapping()` ?

**Comment by MonZop** [comment]
You have found an error, but unfrtunately it is not the one that stops the calculation of the surface.
By analogy with line 395, it seems that bootstrapping () should be correct.
Thanks

**Comment by zeffii** [comment]
Quite right, the issue tracker is for all possible issues. This issue can be closed
