### ISSUE TITLE
Proposed package structure and code style changes

### ISSUE THREAD

**Issue by zeffii** [MonZop/BioBlender#7]
## Structure

This issue is to describe an alternative structure of the addon. The intention is to separate concepts which do not need to be coupled merely because they rely on a global variable to carry state. It's a lot of work to pull these things apart and i'm not asking anyone else to do it, in fact I will do this in another experimental Branch called "BB2_273_modular". After the addon is compatible with 2.73, and all test molecules import correctly

I'm thinking something like
```
bio_modules/ui/..              # all panels
bio_modules/operators/..       # all operators
bio_modules/utils/..           # all decoupled functions
bio_modules/constants/..       # all huge tables / dicts 
bio_test_molecules/..
bin/..
tmp/..
data/..
__init__.py
BioBlender2.py                 # should shrink significantly or disappear
License.txt
mouse26.txt
README.md

```

## Code Style 

Once the structure is modular and working, It may be wise to start thinking of how the code is written:

- I would like to move to `spaces` instead of `tabs` for indentation (but will hold off for now)
- use more aliasing, all these chained `.` lookups make the code look more imposing than it is.
- propose max line length of 100
- propose limits to how deeply if statements are nested ( beyond three becomes a pain )
- ideally we start using pep8 / pylint style checker, it is python after all.
- we use `os.path.join()` instead of joining `os.sep` manually.

    ```python
    fullpath =  `path + os.sep + dir1 + os.sep + dir2 + os.sep + filename`
    # would become
    fullpath = os.path.join(path, dir1, dir2, filename)

    ```
- Use the modern string formatting features of python
- Add more [elaborate Exception handling messages](http://stackoverflow.com/a/3702847/1243487), the line number / line would be more helpful

--------------

I will add more to this thread as it comes to me.

**Comment by zeffii** [comment]
ultra minimal pdb import routine (mere experiment, 5 took five minutes to code) 
https://gist.github.com/zeffii/9f71c319ff8f245df43e 
![fast_import](https://cloud.githubusercontent.com/assets/619340/5946897/6bd23df4-a739-11e4-874a-b8c3fceeb7ef.gif)

**Comment by zeffii** [comment]
import time below 0.2 second
![image](https://cloud.githubusercontent.com/assets/619340/5947944/301fe790-a741-11e4-8d89-01d638b0ab9f.png)
using dupl-verts, each vertex of the objects `atoms_C, atoms_N, atoms_O, atoms_P, atoms_S` gives the location of an atom of that type. Each atom (from my limited understanding) is represented by  a radius (first element of `scale_cov` dictionary). and a common color (color not yet done)

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/5948802/273150f4-a748-11e4-9cdc-2cd4770d27c9.png)
this one takes radii and comon color into account. fast import. could probably reduce memory footprint by adding subsurf to the child atom.

here script:
https://gist.github.com/zeffii/21fdce98b73285621f83

next script will include checks for existing materials, and a section to wipe existing meshes so the script can be run repeatedly.

**Comment by zeffii** [comment]
the above experiment should work if you set the render method to Cycles.

**Comment by MonZop** [comment]
Nice work, thanks.
But I have to remark that the import of atoms is just a preliminary step: the entire point of BioBlender is to show molecules NOT as the collection of atoms, but as the continuous volume, which is defined by those atoms, i.e., the molecular surface. The 'coloring' of this surface is, once agin, determined by the underlying atoms, but integrated using a library of vlaues and a formula that attributes to the surface (vertex by vertex) the value resulting from the calculation.

**Comment by MonZop** [comment]
The second major point of BioBlender, is the molecular motion. 
Just like legs and arms in 'normal' carachters, atoms in a molecule can move, but are not entirely free: for this reason we used bones in the place of each chemical bond, and provided that:
- bones cannot change length
- planar angles of the joints cannot change
- only rotation along the joint axis is permitted.
To this, it is necessary to add the collision control (something that could not be done using instances of spheres).
All this is achieved using the Blender Game Engine. Also this can be changed, of course, but at the moment it seems more reasonable to fix the present BioBlender, because we have already demonstrated that it produces scientifically sound results.

**Comment by zeffii** [comment]
@MonZop The more i know about pdb the better I can judge the data structures it has been parsed into by BB2. It isn't my intention to write a full pdb importer. ([Importers exist already but represent only static shapes](http://wiki.blender.org/index.php/Extensions:2.6/Py/Scripts/Import-Export/PDB)), not the convolving animated entities BioBlender is aimed at showing. This is a first step to figuring out a way to animate the data as vertices of an object, instead of directly using objects.

**Comment by zeffii** [comment]
@MonZop but before any of the experiments here are taken further, I agree that the current state of BB2 should at least import the test molecules without failures. It would really help to have brief communication with whoever wrote the lines I highlighted in https://github.com/MonZop/BioBlender/issues/8

**Comment by MonZop** [comment]
The lines are part of the code that builds the joints, while creating the atoms.
The first time it was written by Mike Pan (it worked), and it was then re-used , slightly modified for BioBledner 1 and 2 by Francesco Milanese (both of them know about this repository, but I will mail them again).
Hope they can help!

**Comment by zeffii** [comment]
@MonZop  do you have the various old source-codes as separate zips leading up to this point? Maybe with a bit of code-archeology I can see where that `modelList` variable got lost..

**Comment by zeffii** [comment]
i'm closing this for now to reduce the noise.

**Comment by mikepan** [comment]
Hi, I was notified of this repo and thought I should chime in:

The lines you are seeing in #8 represent rigid body joints. They are used to animated the molecule inside the game engine. They are safe to remove if you have another way of simulating them physically, The BGE isn't very deterministic with simulating them anyways.

**Comment by zeffii** [comment]
Hi @mikepan, thanks for the heads up. I haven't looked closely at the rigging or game engine code yet. Perhaps may I fire the occasional question in your direction? I don't mind doing the coding of course :) but the BGE and Rigging aren't my areas of expertise.

Providing the physics simulation via other means is not a primary concern. Of course I have some curiosity towards trying the simulation using numpy and modules

**Comment by mikepan** [comment]
Sure, by all means. I think you are on the right track with doing as much of the simulation as possible in code, and using dupliverts in Blender for drawing. API calls in Blender is really slow, especially when object updates are involved. That was the main reason why importing something tiny takes 30 seconds, It was all in the scene update.

**Comment by MonZop** [comment]
In this respect, with a colleague who is a mathematician, we are devising a procedure to calculate protein motion trhough a Monte Carlo procedure using quaternions (all coded in Pthon/numpy/biopython). As soon as we see it working, we can try to introduce it in BioBlender. 
It is meant to provide both random motion and directed transition between fixed conformations.

**Comment by zeffii** [comment]
I wonder then if it's worth my time trying to get the BGE stuff working. Offloading to a dedicated process to produce a motion-cache and bond-cache seems a natural progression, and would allow the use of dedicated hardware (CUDA..GPU) and dedicated routines.

**Comment by mikepan** [comment]
BGE doesn't support geometry instancing the way Blender does. So you might
run into problems. Personally I would just focus on native Blender.

**Comment by zeffii** [comment]
So we agree, using the BGE is not the way forward, but caching positions and bonds via other means (method alluded to by @MonZop ) would be most desirable.
