### ISSUE TITLE
Do all test molecules import correctly in Blender 2.68?

### ISSUE THREAD

**Issue by zeffii** [MonZop/BioBlender#8]
In the [273_Compatible branch](https://github.com/MonZop/BioBlender/tree/273_Compatible), the following test molecules import OK. But very slow for reasons which are known

~~in 2.73+ currently the imports look as follows:~~

[01_CaM_Protein3Conformations_wH.PDB]()
------------------------
![image](https://cloud.githubusercontent.com/assets/619340/5939633/ab5273ce-a705-11e4-8017-730b9dce5f82.png)

no errors!

-------------------------

[02_4IHV_dsDNA.pdb]() Fixed!
------------------------

![image](https://cloud.githubusercontent.com/assets/619340/5939399/aa26054e-a703-11e4-92e2-51187f49bd72.png)

with this abbreviated output
```
DA
---calculating----
parent
["C1'", 'C']
returned
Import Failed: ('Unable to generate all bonds and constraints:', NameError("name 'modelList' is not defined",))

```
remark:
Here the reference to `modelList` comes from nowhere, Do you know what it should reference? The term `modelList` only occurs 2 times in the whole of BioBlender2.py, but doesn't seem to be assigned at any point. Perhaps that should be `tmpModel` instead?

edit:
after test replacing `modelList` with `tmpModel` it is evident that _that_ wasn't a simple typo.

https://github.com/MonZop/BioBlender/blob/master/BioBlender2.py#L947-L952 (references `modelList`) . ~~but a few lines up from it the same mechanism references `tmpModel` instead .
https://github.com/MonZop/BioBlender/blob/master/BioBlender2.py#L915-L922~~

-------------------------

[03_3IV5_DNA_proteinComplex.pdb]() Fixed!
------------------------

![image](https://cloud.githubusercontent.com/assets/619340/5939948/e25dcbd2-a707-11e4-9afd-f75e476847e0.png)

error abbreviated:
```
parent
["C1'", 'C']
returned
Import Failed: ('Unable to generate all bonds and constraints:', NameError("name 'modelList' is not defined",))
```
again with reference to `modelList`

-------------------------

[04_Dimer_1A4U.pdb]()
------------------------

![image](https://cloud.githubusercontent.com/assets/619340/5940274/2d5200d4-a70a-11e4-9812-5d36371ae490.png)

this takes a catastrophic 3 minutes, but no errors

------------------------------

[05_glycoprotein_4AY9_FSH.pdb]()
-------------------------
![image](https://cloud.githubusercontent.com/assets/619340/5940714/fc9a6956-a70c-11e4-8870-04060e66d790.png)

no errors

----------------------

[06_PLipid_.pdb]()
-----------------------
![image](https://cloud.githubusercontent.com/assets/619340/5940805/706c5dd0-a70d-11e4-9b27-54cacf3a43b4.png)

error abbreviated:
```
appending file
core_create_Models
Import Failed: ('Unable to generate all bonds and constraints:', UnboundLocalError("local variable 'parent' referenced before assignment",))
```
remark, exceptions without line-numbers are annoying. ~~I will add this feature eventually, but here it might be ok to assume that wherever parent is assigned a value, that code isn't actually executed, one of the loops where this happens probably doesn't loop over anything.~~ After adding line numbers to exception handling, it appears that the bondLookUp for a specific atom fails to produce a parent, and that's why parent is _referenced before assignment_. See further down for more about this error

https://github.com/MonZop/BioBlender/blob/master/BioBlender2.py#L924-L952

**Comment by MonZop** [comment]
I'm checking all the pdb files with previous BioBlender. If necessary, I will adjust the files to make them readable.

**Comment by MonZop** [comment]
The PDB files 02_4IHV_dsDNA and 03_3IV5_DNA_proteinComplex have the same problem: thay fail to build the DNA bases.
I have changed the file 02, to make it simpler (but with same problems), and faster to test.

**Comment by zeffii** [comment]
May I suggest if you edit a pdb , that you suffix the name with `EDITED` or `REDUX`, and keep the originals to test against?

**Comment by zeffii** [comment]
At the moment I don't know where the reference to modelList comes from, can we ask the the coder what the intention of https://github.com/MonZop/BioBlender/blob/master/BioBlender2.py#L947-L952 was?

**Comment by zeffii** [comment]
@MonZop OK i downloaded version BB267___PDBimport.py (1.0) and see in:
`core_parsePDB(filePath)`, there's a `global modelList` :)  So if they don't respond, at least I will know where to start unraveling it.

**Comment by zeffii** [comment]
Progress!
![image](https://cloud.githubusercontent.com/assets/619340/5959993/aaa4e39e-a7d2-11e4-8449-25faa898a21d.png)

```
						if targetKey == "atom":
							print("TargetKey not set, will skip Rigid Body Joint")
						else:
							obj = bpy.data.objects[entry[0]]

							# line = modelList[0][entry[0]]
							line = tmpModel[entry[0]]
							
							obj.location=line.get("loc")

							# line = modelList[0][targetKey]
							line = tmpModel[targetKey]

							nextEntry.location=line.get("loc")
							addRigidBodyRotamer(obj,bpy.data.objects[targetKey])
```

**Comment by MonZop** [comment]
Good!
Do I understand that the molecule is built, but without the joints?

**Comment by zeffii** [comment]
Good question, with that portion of the code now seemingly doing what it was supposed to i'll continue with the differential of BB1 and BB2.

Maybe you could try the 273_compatibility branch, are you familiar with how to try various branches of the same repository?

**Comment by zeffii** [comment]
## 06_PLipid_.pdb

not yet fixed.

After adding Line / Line number messages to the Exception handling In my branch, there is more information. 
```
Traceback (most recent call last):
  File "C:\blender_trunk\2.73\scripts\addons_contrib\BioBlender\BioBlender2.py", line 919, in core_createModels
    parent = bondLookUp(atom=atom, amac=amac)
  File "C:\blender_trunk\2.73\scripts\addons_contrib\BioBlender\BioBlender2.py", line 1060, in bondLookUp
    return parent
UnboundLocalError: local variable 'parent' referenced before assignment

Import Failed: ('Unable to generate all bonds and constraints:', UnboundLocalError("local variable 'parent' referenced before assignment",))
```

**Comment by zeffii** [comment]
@MonZop in the pdb , excerpt below
```
ATOM     61  H11 POP X   2      12.954   4.010  20.151  0.00  0.00           H 
ATOM     62  H12 POP X   2      12.908   4.056  18.346  0.00  0.00           H 
ATOM     63  H21 POP X   2      11.094   2.474  18.302  0.00  0.00           H 
ATOM     64  H22 POP X   2      11.134   1.252  19.780  0.00  0.00           H 
ATOM     65  H23 POP X   2      11.191   3.034  20.030  0.00  0.00           H 
ATOM     66  H31 POP X   2      12.983   0.382  20.400  0.00  0.00           H 
ATOM     67  H32 POP X   2      14.549   1.235  20.254  0.00  0.00           H 
ATOM     68  H33 POP X   2      13.140   1.903  21.321  0.00  0.00           H 
ATOM     69  H41 POP X   2      14.428   1.197  18.028  0.00  0.00           H 
ATOM     70  H42 POP X   2      12.912   0.353  18.102  0.00  0.00           H 
ATOM     71  H43 POP X   2      13.118   1.979  17.072  0.00  0.00           H 
```
`H 11, 12, 21, 22, 23, 31, 32, 33, 41, 42, 43`  all refer to the quantized state of a H atom?

**Comment by zeffii** [comment]
OK, this section of the code is identical to the BioBlender1.0 ( http://www.bioblender.eu/Database/BB267.zip ) maybe it's time to look at the source of BioBlender 0.6.

**Comment by MonZop** [comment]
The P_lipid is a phopspho-lipid, it has two carbon chains conncted at the head with a group containing a phosphorus atom and several oxygens (my apologies to any chemist that may read this).
I suspect that the reason why it fails to import is that in the bonds library it is not listed. Before BB2, the chemical bonds were included only on request.

**Comment by zeffii** [comment]
Maybe you could describe the process which was used to make add bonds to the `bondLookUp` function), so as to automate the process from a library? I imagine such library does exist but it may be big?

**Comment by MonZop** [comment]
Sorry, I do not even understand the question: but it may help if I add the lipid to the library?

**Comment by zeffii** [comment]
yep. perfect

**Comment by MonZop** [comment]
My understading is that the bonds are considered of two tipes: MainChain and SideChain (or Amino-acid, Amac).
The bonds of the main chain are easy to build because they are linear: for proteins it is a single chain of bonds connecting the atoms designed as (N, CA, C)n in a single row; for nucleic acids it is also a single chain of bonds, which connect atoms designed as (P, O5', C5', C4', C3', O3')n.
The main chain is defined (I think) in the main program (BioBlender2.py).
 
Next are the SideChians: for proteins there are 20 different AminoAcids (Ala, Arg,Asn, Asp etc.). They invariably start with a CB, bound to the corresponding CA, and proceed in various combiantion of atoms. 
For Nucleic Acids, they are the 4 Basis (ACTG) + U, and stem from  C3' and proceed with C2' etc..
For what I recall, the specific bonds of the side chains were all stored in a library (which I cannot locate in the BioBlender folder, maybe you do?).

The Lipid is not considered (yet). I suggest that we concentrate for now on proteins and nucleic acids, and reconsider how to deal with lipids for a following time. I will remove the P_lipid file from the TestMolecules folder, in order to avoid confusion.

**Comment by zeffii** [comment]
These are the only lookups I see:
https://github.com/MonZop/BioBlender/blob/master/BioBlender2.py#L186-L224
https://github.com/MonZop/BioBlender/blob/master/BioBlender2.py#L976-L1070  <-- perhaps?

OK i will ignore the Lipid.

**Comment by MonZop** [comment]
FOUND!
The first part (L186-L224) define the value of the lipophilic potential for each atom (not relevant here), but the seond is exactly the bond connections.
To make a general structure for lipids is more complex, because they are not as modular as proteins and nucelic acids. Let's just ignore for now, and/or set BB to build the molecule with atoms but without joints (bonds).

**Comment by zeffii** [comment]
I think all `bones` are created, at least this feature doesn't appear to be broken from what I can make out.

**Comment by zeffii** [comment]
The imports do seem to work, given restrictions. Bones / Joints should be a separate issue or more _specific_ issue

**Comment by zeffii** [comment]
The imports do seem to work, given restrictions. Bones / Joints should be a separate issue or more _specific_ issue
